# config/__init__.py
from .settings import (
    BASE_DIR, DATA_DIR, PHOTOS_DIR, TEMP_FACES_DIR,
    CAMERA_INDEX, CAPTURE_DURATION, SAVE_INTERVAL,
    FACE_THRESHOLD, FACE_MODEL, DISTANCE_METRIC,
    ADMIN_PASSWORD, GROUPS, SUPPORTED_EXT
)

__all__ = [
    "BASE_DIR", "DATA_DIR", "PHOTOS_DIR", "TEMP_FACES_DIR",
    "CAMERA_INDEX", "CAPTURE_DURATION", "SAVE_INTERVAL",
    "FACE_THRESHOLD", "FACE_MODEL", "DISTANCE_METRIC",
    "ADMIN_PASSWORD", "GROUPS", "SUPPORTED_EXT"
]